/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capabilities
         * @description What this deployment can run, so a client offers only that.
         */
        get: operations["capabilities_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Companies
         * @description Every company the tools know, by ticker.
         */
        get: operations["companies_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evals
         * @description Eval runs, newest first.
         */
        get: operations["evals_evals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare
         * @description `candidate` judged against `baseline` by the gate. Runs it refuses come
         *     back with `comparable: false` and the reasons, not as an error.
         */
        get: operations["compare_evals_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evals/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Eval
         * @description One eval run with its per-case scores.
         */
        get: operations["get_eval_evals__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness only. Never checks a dependency — a probe that fails on a
         *     database blip restarts a healthy pod.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Investigate */
        post: operations["investigate_investigate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runs
         * @description Saved runs, newest first.
         */
        get: operations["runs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description One saved run: the question, settings, answer, claims, evidence and
         *     tool calls.
         */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Run
         * @description A saved run as a JSON file to download.
         */
        get: operations["export_run_runs__run_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Feedback
         * @description A 👍/👎 and an optional note on a saved run, replacing any earlier one.
         */
        post: operations["run_feedback_runs__run_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify
         * @description A verdict for each claim, and what they add up to. Claims the numeric
         *     verifier can't read come back UNVERIFIABLE; an answer with no claims is
         *     UNVERIFIABLE as a whole.
         */
        post: operations["verify_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentResult
         * @description What every runtime produces, regardless of which one ran the case.
         */
        AgentResult: {
            /** Answer */
            answer: string;
            /** Case Id */
            case_id: string;
            /**
             * Claims
             * @default []
             */
            claims: components["schemas"]["Claim"][];
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Cost Eur */
            cost_eur: number;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Error */
            error: string | null;
            /** Evidence */
            evidence: string[];
            /**
             * Evidence Items
             * @default []
             */
            evidence_items: components["schemas"]["Evidence"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "single" | "multi";
            /** Runtime */
            runtime: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Tool Calls */
            tool_calls: components["schemas"]["ToolCall"][];
        };
        /**
         * Capabilities
         * @description Body of `GET /capabilities`.
         */
        Capabilities: {
            data_source: components["schemas"]["DataSource"];
            /** Default Mode */
            default_mode: string;
            /** Default Runtime */
            default_runtime: string;
            /** Run History */
            run_history: boolean;
            /** Runtimes */
            runtimes: components["schemas"]["RuntimeCapability"][];
        };
        /**
         * CaseScore
         * @description Per-case evaluation result.
         */
        CaseScore: {
            /** Answer Score */
            answer_score: number;
            /** Case Id */
            case_id: string;
            /** Citation Precision */
            citation_precision?: number | null;
            /** Claim Support Rate */
            claim_support_rate?: number | null;
            /** Cost Eur */
            cost_eur: number;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Failure Class */
            failure_class?: ("retrieval" | "reasoning" | "tool_use" | "budget" | "runtime_error" | "none") | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /**
             * Faithfulness Judge Failed
             * @default false
             */
            faithfulness_judge_failed: boolean;
            /**
             * Judge Failed
             * @default false
             */
            judge_failed: boolean;
            /** Notes */
            notes: string;
            /** Rubric Scores */
            rubric_scores: {
                [key: string]: number;
            };
            /** Task Completion */
            task_completion: boolean;
            /** Tool Call Accuracy */
            tool_call_accuracy: number;
            /**
             * Tool Names
             * @default []
             */
            tool_names: string[];
            /** Tool Path Equivalent */
            tool_path_equivalent: boolean;
            /** Tool Path Exact */
            tool_path_exact: boolean;
            trajectory?: components["schemas"]["TrajectoryScore"] | null;
            /** Verifications */
            verifications?: components["schemas"]["ClaimVerification"][] | null;
        };
        /**
         * Claim
         * @description A statement in the answer and the evidence refs it rests on.
         */
        Claim: {
            /** Evidence Refs */
            evidence_refs: string[];
            /**
             * Importance
             * @enum {string}
             */
            importance: "key" | "supporting";
            /** Text */
            text: string;
        };
        /**
         * ClaimVerification
         * @description The verdict on one claim, with the rows it came from and the numbers
         *     compared (ADR 0034). `claimed_value` and `recomputed_value` share a unit:
         *     percentage points for growth and ratios, the row's unit for a level.
         *     `tolerance` is the largest difference still counted as a match.
         */
        ClaimVerification: {
            /** Claim Id */
            claim_id: string;
            /** Claimed Value */
            claimed_value: number | null;
            /** Evidence Refs */
            evidence_refs: string[];
            /** Reasoning */
            reasoning: string;
            /** Recomputed Value */
            recomputed_value: number | null;
            /** Text */
            text: string;
            /** Tolerance */
            tolerance: number | null;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "SUPPORTED" | "PARTIALLY_SUPPORTED" | "UNSUPPORTED" | "CONTRADICTED" | "STALE" | "UNVERIFIABLE";
        };
        /**
         * Company
         * @description A company the tools have data for.
         */
        Company: {
            /** Company Id */
            company_id: string;
            /** Name */
            name: string;
        };
        /**
         * CompanyList
         * @description Body of `GET /companies`, sorted by ticker.
         */
        CompanyList: {
            /** Companies */
            companies: components["schemas"]["Company"][];
        };
        /**
         * Comparison
         * @description `candidate` judged against `baseline`.
         */
        Comparison: {
            /** Baseline */
            baseline: string;
            /** Candidate */
            candidate: string;
            /** Comparable */
            comparable: boolean;
            /** Metrics */
            metrics: components["schemas"]["MetricRow"][];
            /**
             * Noise Rule
             * @default
             */
            noise_rule: string;
            /** Reasons */
            reasons: string[];
            /** Settings */
            settings: components["schemas"]["SettingRow"][];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /**
         * DataSource
         * @description Where the tools' data comes from: SEC EDGAR or synthetic fixtures.
         */
        DataSource: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "edgar" | "fixture";
            /** Snapshot */
            snapshot: string;
        };
        /**
         * EvalList
         * @description Body of `GET /evals`, newest first.
         */
        EvalList: {
            /** Runs */
            runs: components["schemas"]["EvalSummary"][];
        };
        /**
         * EvalRun
         * @description A full evaluation run, written to evals/results/<run_id>.json.
         */
        EvalRun: {
            /** Aggregate */
            aggregate: {
                [key: string]: number;
            };
            /** Case Scores */
            case_scores: components["schemas"]["CaseScore"][];
            /** Dataset */
            dataset: string;
            /** Dataset Attribution */
            dataset_attribution: string;
            /** Dataset License */
            dataset_license: string;
            /** Mode */
            mode: string;
            /** Model Config Hash */
            model_config_hash: string;
            /** Prompt Hashes */
            prompt_hashes: {
                [key: string]: string;
            };
            /** Retrieval Labels Hash */
            retrieval_labels_hash?: string | null;
            /**
             * Routing
             * @default false
             */
            routing: boolean;
            /** Rubric Version */
            rubric_version: string;
            /** Run Id */
            run_id: string;
            /** Runtime */
            runtime: string;
            /**
             * Timestamp Utc
             * Format: date-time
             */
            timestamp_utc: string;
            /** Tool Data Snapshot */
            tool_data_snapshot?: string | null;
            /** Total Cost Eur */
            total_cost_eur: number;
            /** Verifier Version */
            verifier_version?: string | null;
        };
        /**
         * EvalSummary
         * @description One row of `GET /evals`: an eval run from `evals/results/`.
         */
        EvalSummary: {
            /** Answer Score Mean */
            answer_score_mean: number | null;
            /** Case Count */
            case_count: number;
            /** Claim Verdicts */
            claim_verdicts?: {
                [key: string]: number;
            } | null;
            /** Cost Per Correct Answer Eur */
            cost_per_correct_answer_eur: number | null;
            /** Dataset */
            dataset: string;
            /**
             * Incomplete
             * @default []
             */
            incomplete: string[];
            /** Mode */
            mode: string;
            /** Routing */
            routing: boolean;
            /** Rubric Version */
            rubric_version: string;
            /** Run Id */
            run_id: string;
            /** Runtime */
            runtime: string;
            /** Task Completion Rate */
            task_completion_rate: number | null;
            /**
             * Timestamp Utc
             * Format: date-time
             */
            timestamp_utc: string;
            /** Total Cost Eur */
            total_cost_eur: number;
        };
        /**
         * Evidence
         * @description One tool row an answer cites, resolved by the server (ADR 0030).
         *
         *     The model cites a row by its `ref`. `verified` is true only when that ref
         *     matches a row a tool returned in the same run; the source details and
         *     `excerpt` then come from that row, never from the model. An unverified
         *     ref keeps only `ref`, with `source_type="unknown"`.
         */
        Evidence: {
            /** Accession */
            accession?: string | null;
            /** Company Id */
            company_id?: string | null;
            /** Content Hash */
            content_hash?: string | null;
            /**
             * Excerpt
             * @default
             */
            excerpt: string;
            /** Filed */
            filed?: string | null;
            /** Form */
            form?: string | null;
            /** Locator */
            locator?: string | null;
            /** Ref */
            ref: string;
            /** Retrieval Score */
            retrieval_score?: number | null;
            /** Section */
            section?: string | null;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "filing_text" | "financial_fact" | "filing" | "company" | "concept" | "unknown";
            /** Tool */
            tool?: string | null;
            /** Verified */
            verified: boolean;
        };
        /**
         * Feedback
         * @description Body of `POST /runs/{run_id}/feedback`: a human label on an answer,
         *     the start of the judge-calibration set (#115).
         */
        Feedback: {
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Rating
             * @enum {string}
             */
            rating: "up" | "down";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Interval
         * @description A 95% interval.
         */
        Interval: {
            /** High */
            high: number;
            /** Low */
            low: number;
        };
        /**
         * InvestigateRequest
         * @description Body of `POST /investigate`.
         *
         *     `mode`/`runtime` are left as plain strings, not a `Literal`, so an
         *     unsupported value reaches the endpoint's own check and comes back as a 422
         *     naming what's unsupported, rather than FastAPI's schema-level 400.
         */
        InvestigateRequest: {
            /** Context */
            context?: {
                [key: string]: unknown;
            };
            /** Mode */
            mode?: string | null;
            /** Question */
            question: string;
            /** Runtime */
            runtime?: string | null;
        };
        /**
         * MetricRow
         * @description One metric of both runs. `verdict` is "same", "better" or "worse" for a
         *     gated metric of comparable runs, and None otherwise.
         */
        MetricRow: {
            /** Band */
            band?: string | null;
            /** Baseline */
            baseline: number | null;
            baseline_interval?: components["schemas"]["Interval"] | null;
            /** Candidate */
            candidate: number | null;
            candidate_interval?: components["schemas"]["Interval"] | null;
            /** Name */
            name: string;
            /** Verdict */
            verdict?: string | null;
        };
        /**
         * ResearchRun
         * @description One finished `POST /investigate`, as the run store keeps it.
         */
        ResearchRun: {
            /** Context */
            context: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Data Source */
            data_source: string;
            feedback?: components["schemas"]["StoredFeedback"] | null;
            /** Mode */
            mode: string;
            /** Question */
            question: string;
            result: components["schemas"]["AgentResult"];
            /** Run Id */
            run_id: string;
            /** Runtime */
            runtime: string;
        };
        /**
         * RetrievalQuality
         * @description How well the agent's own searches found the passages labelled relevant
         *     for its case (#116). Its searches are replayed in first-seen order;
         *     `recall` counts everything retrieved, the rest the first five.
         */
        RetrievalQuality: {
            /** Mrr At 5 */
            mrr_at_5: number;
            /** Ndcg At 5 */
            ndcg_at_5: number;
            /** Precision At 5 */
            precision_at_5: number;
            /** Recall */
            recall: number;
            /** Retrieved Count */
            retrieved_count: number;
        };
        /**
         * RunList
         * @description Body of `GET /runs`, newest first.
         */
        RunList: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
        };
        /**
         * RunSummary
         * @description One row of `GET /runs`.
         */
        RunSummary: {
            /** Claim Count */
            claim_count: number;
            /** Confidence */
            confidence: string;
            /** Cost Eur */
            cost_eur: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Failed */
            failed: boolean;
            /** Feedback */
            feedback: ("up" | "down") | null;
            /** Mode */
            mode: string;
            /** Question */
            question: string;
            /** Run Id */
            run_id: string;
            /** Verified Evidence Count */
            verified_evidence_count: number;
        };
        /**
         * RuntimeCapability
         * @description A runtime and whether this deployment can run it.
         */
        RuntimeCapability: {
            /** Modes */
            modes: string[];
            /** Name */
            name: string;
            /** Reason */
            reason?: string | null;
            /** Supported */
            supported: boolean;
        };
        /**
         * SettingRow
         * @description One setting of both runs.
         */
        SettingRow: {
            /** Baseline */
            baseline: string;
            /** Candidate */
            candidate: string;
            /** Name */
            name: string;
        };
        /**
         * StoredFeedback
         * @description Feedback as stored with its run.
         */
        StoredFeedback: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Rating
             * @enum {string}
             */
            rating: "up" | "down";
        };
        /**
         * ToolCall
         * @description One tool invocation, in the order it was made.
         */
        ToolCall: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Status */
            status: string;
            /** Tool */
            tool: string;
        };
        /**
         * TrajectoryScore
         * @description The run path of one case, scored step by step from its recorded trace
         *     without a model call (#116). None means not applicable or not measurable
         *     for this case.
         */
        TrajectoryScore: {
            /** Argument Correctness */
            argument_correctness?: number | null;
            /** Efficiency */
            efficiency?: number | null;
            /** Evidence Sufficiency */
            evidence_sufficiency?: number | null;
            /** Final Correctness */
            final_correctness?: number | null;
            /** Grounding */
            grounding?: number | null;
            /** Recovery */
            recovery?: number | null;
            retrieval_quality?: components["schemas"]["RetrievalQuality"] | null;
            /** Tool Selection */
            tool_selection?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificationReport
         * @description Every claim of one answer checked, and what that adds up to (ADR 0035).
         *
         *     The scores are None when nothing could be measured. `overall_verdict` is
         *     the worst claim's verdict, UNVERIFIABLE for an answer with no claims.
         */
        VerificationReport: {
            /** Claims */
            claims: components["schemas"]["ClaimVerification"][];
            /** Correctness Score */
            correctness_score?: number | null;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Freshness Score */
            freshness_score?: number | null;
            /** Grounding Score */
            grounding_score?: number | null;
            /**
             * Overall Verdict
             * @enum {string}
             */
            overall_verdict: "SUPPORTED" | "PARTIALLY_SUPPORTED" | "UNSUPPORTED" | "CONTRADICTED" | "STALE" | "UNVERIFIABLE";
        };
        /**
         * VerifyRequest
         * @description Body of `POST /verify`: an answer's claims and the tool rows they rest
         *     on. A claim that cites refs is checked against those rows only; one that
         *     cites none, against every row. Rows are `get_financial_fact` output.
         */
        VerifyRequest: {
            /** Claims */
            claims?: components["schemas"]["Claim"][];
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capabilities_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    companies_companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyList"];
                };
            };
        };
    };
    evals_evals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalList"];
                };
            };
        };
    };
    compare_evals_compare_get: {
        parameters: {
            query: {
                baseline: string;
                candidate: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eval_evals__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    investigate_investigate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    runs_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_runs__run_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_feedback_runs__run_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Feedback"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
