apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "recon-agent.fullname" . }}
  labels:
    {{- include "recon-agent.labels" . | nindent 4 }}
data:
  RECON_API_MAX_CONCURRENCY: {{ .Values.env.maxConcurrency | quote }}
  RECON_API_REQUEST_TIMEOUT_S: {{ .Values.env.requestTimeoutS | quote }}
