{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "recon-agent.postgresFullname" . }}
  labels:
    {{- include "recon-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres-dev
spec:
  type: ClusterIP
  selector:
    app: recon-agent-postgres-dev
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
{{- end }}
